name: CI

on: 
  push:
    branches: 
    - master

jobs:
  testing:
    runs-on: ubuntu-latest
    
    steps: 
    - name: Print Hello Message
      run: echo "Hello wolrd testing"
      
    - name: Show files from current folder
      run: ls -la
      
    - name: Git clone repo
      uses: actions/checkout@v1
      
    - name: Show files from current folder
      run: ls -la
  deploy:
    runs-on: ubuntu-latest
    needs: [testing]
    
    steps: 
    - name: Print Hello Message
      run: echo "Hello wolrd deploy"
      
    - name: Test packages if ther are there 1
      run: aws --version
      
    - name: Test packages if ther are there 2
      run: zip --version
      
    - name: Where we are and what we have
      run: pwd | ls -la
      
    - name: Passgen
      run: python passgen.py
  
    
